[project]
name = "blas-testing"
version = "1.0.0"
description = "A pixi project for testing compilation and running blas with various backends"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[environments]
mklenv = {features = ["mklenv"], no-default-feature = true }

[feature.mklenv.dependencies]
libblas = { version = "*", build = "*mkl" }
liblapack = { version = "*", build = "*mkl" }
mkl-devel = "*"
cmake = ">=3.20.0"
ninja = "*"

[feature.mklenv.target.linux-64.dependencies]
gcc = "*"
gfortran = "*"

[feature.mklenv.target.win-64.dependencies]
vs2022_win-64 = "*"
#ifx_win-64 = "*"
fortran-compiler = "*"

[feature.mklenv.tasks]
# Build tasks
configure = "cmake -S . -B build -G Ninja"
build = "cmake --build build"
clean = "rm -rf build"

# Run tasks
run-cpp-dgemm = "./build/src/cpp/dgemm/dgemm_example"
run-fortran-dgemm = "./build/src/fortran/dgemm/dgemm_example"

# Combined tasks
build-and-run-cpp = { depends-on = ["build", "run-cpp-dgemm"] }
build-and-run-fortran = { depends-on = ["build", "run-fortran-dgemm"] }
run-all = { depends-on = ["run-cpp-dgemm", "run-fortran-dgemm"] }