[project]
name = "blas-testing"
version = "1.0.0"
description = "A pixi project for testing compilation and running blas with various backends"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[environments]
mklenv = {features = ["mklenv"], no-default-feature = true }
oblasenv = {features = ["oblasenv"], no-default-feature = true }

[feature.mklenv.dependencies]
libblas = { version = "*", build = "*mkl" }
liblapack = { version = "*", build = "*mkl" }
mkl-devel = "*"
cmake = ">=3.20.0"
ninja = "*"

[feature.mklenv.target.linux-64.dependencies]
gcc = "*"
gfortran = "*"

[feature.mklenv.target.win-64.dependencies]
vs2022_win-64 = "*"
#ifx_win-64 = "*"
fortran-compiler = "*"

[feature.oblasenv.dependencies]
libblas = { version = "*", build = "*openblas" }
liblapack = { version = "*", build = "*openblas" }
openblas = "*"
cmake = ">=3.20.0"
ninja = "*"

[feature.oblasenv.target.linux-64.dependencies]
gcc = "*"
gfortran = "*"

[feature.oblasenv.target.win-64.dependencies]
vs2022_win-64 = "*"
fortran-compiler = "*"

[feature.mklenv.tasks]
# Build tasks
configure = "cmake -S . -B build-mkl -G Ninja"
build = "cmake --build build-mkl"
clean = "cmake -E remove_directory build-mkl"

# Combined tasks
build-and-run-cpp = { depends-on = ["configure", "build", "run-cpp-dgemm"] }
build-and-run-fortran = { depends-on = ["configure", "build", "run-fortran-dgemm"] }
run-mkl = { depends-on = ["build-and-run-cpp", "build-and-run-fortran"]}
run-all = { depends-on = ["run-cpp-dgemm", "run-fortran-dgemm"] }

# Run tasks for different platforms
[feature.mklenv.target.win-64.tasks]
run-cpp-dgemm = "build-mkl/bin/cpp_dgemm_example.exe"
run-fortran-dgemm = "build-mkl/bin/fortran_dgemm_example.exe"
check-build = "dir build-mkl/bin"
show-env = "set | grep CONDA"

[feature.mklenv.target.linux-64.tasks]
run-cpp-dgemm = "./build-mkl/bin/cpp_dgemm_example"
run-fortran-dgemm = "./build-mkl/bin/fortran_dgemm_example"
check-build = "ls -la ./build-mkl/bin"

# Duplicate tasks for OpenBLAS environment
[feature.oblasenv.tasks]
configure = "cmake -S . -B build-openblas -G Ninja"
build = "cmake --build build-openblas"
clean = "cmake -E remove_directory build-openblas"
run-openblas = "build-openblas/bin/cpp_openblas_example"
run-os = { depends-on = ["configure","build", "run-cpp-openblas", "build-and-run-fortran"]}

[feature.oblasenv.target.win-64.tasks]
run-cpp-openblas = "build-openblas/bin/cpp_openblas_example.exe"
check-build = "dir build-openblas/bin"

[feature.oblasenv.target.linux-64.tasks]
run-cpp-openblas = "./build-openblas/bin/cpp_openblas_example"
check-build = "ls -la ./build-openblas/bin"